### ISSUE TITLE
Syncing from Github never completes

### ISSUE THREAD

**Issue by matthewjf** [faros-ai/faros-community-edition#315]
**Describe the bug**
Hi there,

I've been trying to setup a connection between Github and Faros and haven't been able to get it to complete. We have a fairly large mono repo and the sync gets stuck on `Syncing stream: pull_requests `. 

I actually tried copying some of the files from airbyte using the instructions from https://docs.airbyte.com/operator-guides/browsing-output-logs/. There's a `pull_requests.yml` file that's 321MB. When I inspect it, it contains the request and response data for pull requests that were created back in 2015. I suspect that the sync is trying to get the full history of pulls requests and is not using the start data the way I expect it to.

**To Reproduce**
1. Create a Github source (private repo)
2. Set the start date to `2023-09-01T00:00:00Z`
3. Create a connection with the Github source and Faros destination
4. Start sync
5. Nothing happens for 20 hours
6. The logs show that the job was canceled because my computer shut itself down

**Expected behavior**
I expect the sync to finish given the start date

**Screenshots and logs**
<img width="709" alt="Screenshot 2023-09-04 at 7 02 35 AM" src="https://github.com/faros-ai/faros-community-edition/assets/16192022/b4123afb-94ab-47e3-938e-75a00c0a90f4">
<img width="1408" alt="Screenshot 2023-09-04 at 7 02 03 AM" src="https://github.com/faros-ai/faros-community-edition/assets/16192022/79a88f87-7ef2-4fc1-b838-79d2b90677ab">

Logs
[9305eb98_eff2_4933_980a_3ec54522104b_logs_25_txt.txt](https://github.com/faros-ai/faros-community-edition/files/12514516/9305eb98_eff2_4933_980a_3ec54522104b_logs_25_txt.txt)

**Deployment**
Local deployment
M1 Mac
Docker version 24.0.5, build ced0996

**Comment by thomas-gerber** [comment]
I think this is unfortunately because of limitations on the open-source [airbyte community github source](https://docs.airbyte.com/integrations/sources/github/#notes). 
I can see 2 possible paths:
1. In Airbyte > Settings > Sources, switch GitHub connector version to `1.0.4`; improvements are regularly made to the source. It *should* not break anything w.r.t mappings to the Faros data model, but we haven't tested it.
2. Alternatively, you can reach out to me on our [public slack](https://community.faros.ai/docs/slack), we have our own closed source for github that we could let you use.
